# -*- coding: utf-8 -*-
"""tdsweek8streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdtBqrcss3upB-k7u0BRrNPtQu7jSjv2
"""

!pip install -q streamlit

import streamlit as st
import numpy as np

st.write("Subtract two numbers:")
X=st.number_input("X")
Y=st.number_input("Y")
Z=X-Y
st.write(Z)